import matplotlib.pyplot as plt
import numpy as np

def generate_graphs(all_metrics):
    frames_x = np.arange(len(all_metrics))
    psnr_vals = [p if p != float('inf') else 50.0 for p in [m['PSNR'] for m in all_metrics]]
    
    # Combined Graph (3x2 grid for 6 metrics)
    plt.figure(figsize=(12, 12))
    
    plt.subplot(3, 2, 1)
    plt.plot(frames_x, [m['MSE'] for m in all_metrics], color='purple')
    plt.title('Mean Square Error (MSE)')
    plt.xlabel('Frame Number')
    plt.ylabel('MSE')
    plt.grid(True)
    
    plt.subplot(3, 2, 2)
    plt.plot(frames_x, psnr_vals, color='green')
    plt.title('Camcorder PSNR over Time')
    plt.xlabel('Frame Number')
    plt.ylabel('PSNR (dB)')
    plt.grid(True)
    
    plt.subplot(3, 2, 3)
    plt.plot(frames_x, [m['SSIM'] for m in all_metrics], color='orange')
    plt.title('Structural Similarity (SSIM)')
    plt.xlabel('Frame Number')
    plt.ylabel('SSIM')
    plt.grid(True)
    
    plt.subplot(3, 2, 4)
    plt.plot(frames_x, [m['BER'] for m in all_metrics], color='red')
    plt.title('Bit Error Rate (BER)')
    plt.xlabel('Frame Number')
    plt.ylabel('BER')
    plt.grid(True)
    
    plt.subplot(3, 2, 5)
    plt.plot(frames_x, [m['Accuracy'] for m in all_metrics], color='blue')
    plt.title('Extraction Accuracy over Time')
    plt.xlabel('Frame Number')
    plt.ylabel('Accuracy')
    plt.grid(True)
    
    plt.subplot(3, 2, 6)
    plt.plot(frames_x, [m['Event_Sync_Error'] for m in all_metrics], color='brown')
    plt.title('Event Synchronization Error')
    plt.xlabel('Frame Number')
    plt.ylabel('Error')
    plt.grid(True)
    
    plt.tight_layout()
    plt.savefig('atsm_metrics_graph.png', dpi=300)
    plt.close()
    
    # Separate Graphs
    plt.figure(figsize=(6, 4))
    plt.plot(frames_x, [m['MSE'] for m in all_metrics], color='purple')
    plt.title('Mean Square Error (MSE)')
    plt.xlabel('Frame Number')
    plt.ylabel('MSE')
    plt.grid(True)
    plt.tight_layout()
    plt.savefig('atsm_metric_mse.png', dpi=300)
    plt.close()

    plt.figure(figsize=(6, 4))
    plt.plot(frames_x, psnr_vals, color='green')
    plt.title('Camcorder PSNR over Time')
    plt.xlabel('Frame Number')
    plt.ylabel('PSNR (dB)')
    plt.grid(True)
    plt.tight_layout()
    plt.savefig('atsm_metric_psnr.png', dpi=300)
    plt.close()
    
    plt.figure(figsize=(6, 4))
    plt.plot(frames_x, [m['SSIM'] for m in all_metrics], color='orange')
    plt.title('Structural Similarity (SSIM)')
    plt.xlabel('Frame Number')
    plt.ylabel('SSIM')
    plt.grid(True)
    plt.tight_layout()
    plt.savefig('atsm_metric_ssim.png', dpi=300)
    plt.close()
    
    plt.figure(figsize=(6, 4))
    plt.plot(frames_x, [m['BER'] for m in all_metrics], color='red')
    plt.title('Bit Error Rate (BER)')
    plt.xlabel('Frame Number')
    plt.ylabel('BER')
    plt.grid(True)
    plt.tight_layout()
    plt.savefig('atsm_metric_ber.png', dpi=300)
    plt.close()
    
    plt.figure(figsize=(6, 4))
    plt.plot(frames_x, [m['Accuracy'] for m in all_metrics], color='blue')
    plt.title('Extraction Accuracy over Time')
    plt.xlabel('Frame Number')
    plt.ylabel('Accuracy')
    plt.grid(True)
    plt.tight_layout()
    plt.savefig('atsm_metric_accuracy.png', dpi=300)
    plt.close()

    plt.figure(figsize=(6, 4))
    plt.plot(frames_x, [m['Event_Sync_Error'] for m in all_metrics], color='brown')
    plt.title('Event Synchronization Error')
    plt.xlabel('Frame Number')
    plt.ylabel('Error')
    plt.grid(True)
    plt.tight_layout()
    plt.savefig('atsm_metric_event_sync_error.png', dpi=300)
    plt.close()
    
    print("Graphs saved successfully as 'atsm_metrics_graph.png' and individual metric PNGs in your current directory!")
